# Generated by Django 3.0 on 2022-11-08 11:26

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220901_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Введите год выпуска', null=True, validators=[reviews.models.year_validator], verbose_name='Год выпуска'),
        ),
    ]
